### ISSUE TITLE
Clarify that Row IDs are returned in the same order/index as the rows added

### ISSUE THREAD

**Issue by activescott** [glideapps/api-docs#2]
WRT https://github.com/glideapps/api-docs/blob/dc2d69f0885ddb9edfee24926db9e570cb351d64/openapi/swagger.json#L99
I assume that I can map the index of the row added in the rquest to the index of the row ID in the response, is that correct? If so, we should clarify. If not, how can we map a row ID to the input row?

Also we should clarify what happens when one row of a batch fails to get added. Is it a different status code? Is the whole batch failed, or did some of the rows get added? What is in rowID response? How do I read the descriptive error message about why it failed to add, etc. etc.

**Comment by rwdaigle** [comment]
Agreed.

re: `unknownColumns` option: https://github.com/glideapps/glide/issues/28119
