### ISSUE TITLE
Two menu popups are displayed at one time in the Members page.

### ISSUE THREAD

**Issue by sudarshanquisitive** [glideapps/api-docs#3]

**Comment by sudarshanquisitive** [comment]
Hi @rwdaigle,
Please check this issue in detail in the below URL. I added this in more detail in the glide-qa repo.
https://github.com/glideapps/glide-qa/issues/817

Thank you,
Sudarshan K.

**Comment by rwdaigle** [comment]
Ah, ok. I think this issue needs to be filed in a different repo? This is the repository for our API docs only.
